del_t: 0.02  # timestep between sim updates
pause_while_planning: false

# agent state
init_x: 0  # initial x-pos 
init_y: 0  # initial y-pos
init_z: 50  # initial z-pos
init_yaw: 0  # initial heading
set_agent_pose_to_plan_request: true  # whether to teleport the agent to the plan request's specified start position
max_omega: 20.0  # drone max angular velocity
max_zvel: 5  # drone max vertical velocity
agent_l: 3  # agent length for visualization
hvel: 25  # agent x-y velocity ; but gets overriden by plan request
vvel: 2  # agent z-velocity

# ground truth targets
set_targets_to_plan_request: true  # whether to reinit targets exactly to the filtered_target means specified in the plan request
sample_targets_from_plan_request: false  # whether to reinit targets to that specified in the plan request sampled from belief


waypoint_threshold: 1  # in meters

K_p: 10  # PID angular proportionality constant
K_p_z: 0.01  # PID z-axis proportionality constant

targets: [] # start ship IDs at 1. angles in radians. speed in m/s  # to use random targets, se this to empty list
  # - {id: 1, x: 3800, y: 1500, heading: 3.14, linear_speed: 3, angular_speed: 0, linear_speed_std: 0.001, angular_speed_std: 0.002}
  # - {id: 2, x: 2000, y: 1001, heading: 0, linear_speed: 2, angular_speed: 0, linear_speed_std: 0.001, angular_speed_std: 0.002}
  # - {id: 1, x: 200, y: 200, heading: 1.50, linear_speed: 5, angular_speed: 0, linear_speed_std: 0.2, angular_speed_std: 0.01}
  # - {id: 2, x: 1600, y: 500, heading: 1.54, linear_speed: 5.1, angular_speed: 0, linear_speed_std: 0.2, angular_speed_std: 0.01}
  # - {id: 2, x: 600, y: -150, heading: 1.54, linear_speed: 0.2, angular_speed: 0, linear_speed_std: 0.2, angular_speed_std: 0.01}
  # - {id: 3, x: 2000, y: 1250, heading: 1.57, linear_speed: 4.8, angular_speed: 0.0, linear_speed_std: 0.2, angular_speed_std: 0.01}
  # - {id: 4, x: 2500, y: 1000, heading: 1.6, linear_speed: 5.3, angular_speed: 0.0, linear_speed_std: 0.2, angular_speed_std: 0.01}
  # - {id: 5, x: 3000, y: 750, heading: 1.7, linear_speed: 4.4, angular_speed: 0.0, linear_speed_std: 0.2, angular_speed_std: 0.01}

# number of random targets 
n_rand_targets: 0  # number of additional random targets. use -1 for no random targets, and want to only use custom list of targets 


# Visualizations
target_mesh: meshes/boat.dae
