init_x: 0  # initial x-pos 
init_y: 0  # initial y-pos
init_z: 110  # initial z-pos
init_psi: 0  # initial heading

max_omega: 0.7  # drone max angular velocity
max_zvel: 5  # drone max vertical velocity

vehicle_l: 3  # vehicle list for visualization

hvel: 30  # vehicle x-y velocity
vvel: 2  # vehicle z-velocity

# number of random targets 
n_rand_targets: 5  # -1 if providing custom list of targets 

del_t: .01  # timestep between sim updates

waypt_threshold: 4

K_p: 10  # PID angular proportionality constant
K_p_z: 0.01  # PID z-axis proportionality constant

# targets:  # start ship IDs at 1. angles in radians. speed in m/s  # to use random targets, se this to empty list
#   - {id: 1, x: 800, y: 500, heading: 0, linear_speed: 10, angular_speed: 0, linear_speed_std: 0, angular_speed_std: 0}
#   - {id: 2, x: 600, y: -500, heading: 0, linear_speed: 10.1, angular_speed: 0, linear_speed_std: 0, angular_speed_std: 0}
#   - {id: 3, x: 1000, y: 0, heading: 0, linear_speed: 9.9, angular_speed: 0.0, linear_speed_std: 0, angular_speed_std: 0}
#   # - {id: 4, x: 1500, y: 0, heading: 0, linear_speed: 4, angular_speed: -0.01, linear_speed_std: 0, angular_speed_std: 0}
#   # - {id: 5, x: 2000, y: 0, heading: 0, linear_speed: 2, angular_speed: 0.01, linear_speed_std: 0, angular_speed_std: 0}

sensor_a: 1
sensor_b: 1
sensor_d: 1
sensor_g: 1
sensor_h: 1

sensor_focal_length: 15
sensor_width: 10
sensor_height: 10
sensor_pitch: 1.13  # 0.349
sensor_yaw: 0
