init_x: 250  # initial x-pos 
init_y: 250  # initial y-pos
init_z: 110  # initial z-pos
init_psi: 0  # initial heading

max_omega: 0.1  # max angular velocity
max_zvel: 5  # max vertical velocity

vehicle_l: 3  # vehicle list for visualization

hvel: 10  # vehicle x-y velocity
vvel: 2  # vehicle z-velocity

# number of random targets 
n_rand_targets: -1  # -1 if providing custom list of targets 

del_t: .1  # timestep between sim updates

waypt_threshold: 5

K_p: 10  # PID angular proportionality constant
K_p_z: 0.01  # PID z-axis proportionality constant

targets:  # start ship IDs at 1. angles in radians. speed in m/s
  - {id: 1, x: 2750, y: 3200, heading: 0.12, linear_speed: 5, angular_speed: 0.2}
  - {id: 2, x: 3250, y: 750, heading: 3.66, linear_speed: 3, angular_speed: -0.2}
  - {id: 3, x: 0, y: 0, heading: -1.2, linear_speed: 3, angular_speed: -0.2}
  - {id: 4, x: 350, y: 2750, heading: 3.66, linear_speed: 3, angular_speed: 0.0}
  - {id: 5, x: 600, y: 100, heading: 0.785, linear_speed: 4, angular_speed: 0.1}

sensor_a: 1
sensor_b: 1
sensor_d: 1
sensor_g: 1
sensor_h: 1

sensor_focal_length: 15
sensor_width: 10
sensor_height: 10
sensor_pitch: 1.13  # 0.349
sensor_yaw: 0