init_x: 250  # initial x-pos 
init_y: 250  # initial y-pos
init_z: 110  # initial z-pos
init_psi: 0  # initial heading

max_omega: 5  # max angular velocity
max_zvel: 5  # max vertical velocity

vehicle_l: 3  # vehicle list for visualization

hvel: 10  # vehicle x-y velocity
vvel: 2  # vehicle z-velocity

# number of random targets 
n_rand_targets: -1  # -1 if providing custom list of targets 

del_t: .1  # timestep between sim updates

waypt_threshold: 5

K_p: 0.01  # PID angular proportionality constant
K_p_z: 0.01  # PID z-axis proportionality constant

targets:
  [[10, 100, [5, 5], true], [100, 100, [5, 5], true], [50, 100, [5, 5], false]]

sensor_a: 1
sensor_b: 1
sensor_d: 1
sensor_g: 1
sensor_h: 1

sensor_focal_length: 15
sensor_width: 10
sensor_height: 10
sensor_pitch: 0.349
sensor_yaw: 0