del_t: 0.02  # timestep between sim updates
pause_while_planning: false

# agent state
init_x: 0  # initial x-pos 
init_y: 0  # initial y-pos
init_z: 50  # initial z-pos
init_yaw: 0  # initial heading
set_agent_pose_to_plan_request: true  # whether to teleport the agent to the plan request's specified start position
max_omega: 20.0  # drone max angular velocity
max_zvel: 5  # drone max vertical velocity
agent_l: 3  # agent length for visualization
hvel: 25  # agent x-y velocity ; but gets overriden by plan request
vvel: 2  # agent z-velocity

# ground truth targets
set_true_targets_to_target_prior_means: true  # whether to reinit targets exactly to the filtered_target means specified in the plan request
sample_true_targets_from_target_priors: false  # whether to reinit targets to that specified in the plan request sampled from belief. should not be mixed with the above

sample_additional_true_targets_from_search_prior: true  # whether to init more targets based on the search prior of the plan request. uses n_rand_targets


waypoint_threshold: 10  # in meters

K_p: 10  # PID angular proportionality constant
K_p_z: 0.01  # PID z-axis proportionality constant

targets: [] # start ship IDs at 1. angles in radians. speed in m/s  # to use random targets, se this to empty list
  # - {id: 1, x: 3800, y: 1500, heading: 3.14, linear_speed: 3, angular_speed: 0, linear_speed_std: 0.001, angular_speed_std: 0.002}

decay_rate: 0.01  # decay rate for target lifespan

# number of random targets 
n_rand_targets: 20  # number of additional random targets. use -1 for no random targets, and want to only use custom list of targets 
rand_heading_range: [-3.14, 3.14]  # uniform min max
rand_linear_speed_range: [0, 5]  # uniform min max
rand_angular_speed_range: [0, 0.001]  # gaussian: mean, std
rand_linear_speed_std: 0.05
rand_angular_speed_std: 0.01


# Visualizations
visualization_scale: 10.0
target_mesh: meshes/boat.dae